services:
  api-server:
    image: ${API_SERVER_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # datasource properties
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # naver maps properties
      NAVER-MAPS_API-KEY-ID: ${NAVER_MAPS_API_KEY_ID}
      NAVER-MAPS_API-KEY: ${NAVER_MAPS_API_KEY}
      # cors
      CORS_ALLOWED-ORIGINS: ${CORS_ALLOWED_ORIGINS}
      # redis
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
    restart: always
#    depends_on:
#      - redis
#  redis:
#    image: redis:7.4.0
#    restart: always
#    ports:
#      - "6379:6379"
