@localhost = localhost:8080
@awshost = {{AWS_HOST}}
@host = {{localhost}}

### CSRF Token 발급
GET http://{{host}}/api/csrf-token
Accept: application/json

> {%
    client.global.set("csrfToken", response.body.csrfToken.token)
%}

### 회원가입
POST http://{{host}}/api/customers
Content-Type: application/json
X-CSRF-TOKEN: {{csrfToken}}

{
  "email": "abc@gmail.com",
  "password": "Password1!"
}

### 로그인
# 로그인 이후 CSRF 토큰이 변경되므로 다른 CSRF가 필요한 API 요청(예: 로그아웃) 전에 CSRF 토큰을 받아서 갱신해야 한다.
POST http://{{host}}/api/login
Content-Type: application/x-www-form-urlencoded
X-CSRF-TOKEN: {{csrfToken}}

username = abc@gmail.com &
password = Password1!

### 로그아웃
POST http://{{host}}/api/logout
X-CSRF-TOKEN: {{csrfToken}}

### 예약 히스토리(slice)
GET http://{{host}}/api/reservations

### 헤어샵 검색 (검색어: '헤어', 범위: 보통 줌 레벨, 즉, 인덱스 튜닝 테스트했던 그 쿼리) (%ED%97%A4%EC%96%B4 = 헤어 url 인코딩)
GET http://{{host}}/api/hairshop?searchTerm=%ED%97%A4%EC%96%B4
    &minLongitude=120.569682&maxLongitude=130.4573773
    &minLatitude=31.5464907&maxLatitude=40.526968
    &size=100&page=0&sort=name,asc
Accept: application/json
